### ISSUE TITLE
Clicking on "Save As" or "Load" will crash on Windows + Kivy 1.7.0

### ISSUE THREAD

**Issue by lietu** [chaosbuffalolabs/ParticlePanda#5]
Now that I have ParticlePanda running in Windows with Kivy 1.7.0, I noticed that both "Save As" and "Load" -buttons cause a crash.

http://pastebin.com/H149HXtH

**Comment by Kovak** [comment]
It looks like this is because layout padding was changed from a numeric property to a list property in 1.7.0

Should be fixed in master now.

**Comment by lietu** [comment]
Confirmed, works fine now. Thanks.
